name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        default: staging
        required: true
        description: Which environment to deploy on?

jobs:
  Deploy:
    name: Deployment to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    if: contains(${{ github.event.inputs.environment }}, 'staging')
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Deploying 
        uses: akhileshns/heroku-deploy@v3.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "staging-the-retro-app"
          heroku_email: "ajit.drag@gmail.com"
          buildpack: "heroku/nodejs"
