name: Push to master

on:
  push:
    branches: 
      - master

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2
    - name: Setting up Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.1
    - name: Install dependencies
      run: yarn
    - name: Unit testing
      run: yarn lerna run test --stream

  build:
    name: Building
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checking out Repository
      uses: actions/checkout@v2
    - name: Setting up Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.18.1
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn lerna run build --stream
  
  deploy:
    name: Deploying App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2
      - name: Deploying 
        uses: akhileshns/heroku-deploy@v3.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "staging-the-retro-app"
          heroku_email: "ajit.drag@gmail.com"
          buildpack: "heroku/nodejs"
